version: '1'
services:
  microservicio-tokens:
    container_name: microservicio-tokens
    image: ingfaraya/desarrollo-full-stack-3-formativa5-tokens:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@legx51juninivtkl_medium?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Octubre$2024
    networks:
      - app-network
    restart: on-failure

  microservicio-recetas:
    container_name: microservicio-recetas
    image: ingfaraya/desarrollo-full-stack-3-formativa4-recetas:latest
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@legx51juninivtkl_medium?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Octubre$2024
    networks:
      - app-network
    restart: on-failure

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - ./sonarqube_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
  
  frontend:
    container_name: frontend
    image: ingfaraya/desarrollo-full-stack-3-sumativa3-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge