version: '1'
services:
  microservicio-tokens:
    container_name: microservicio-tokens
    image: ingfaraya/desarrollo-full-stack-3-formativa4-tokens:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@legx51juninivtkl_medium?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Octubre$2024
    networks:
      - app-network
    restart: on-failure

  microservicio-recetas:
    container_name: microservicio-recetas
    image: ingfaraya/desarrollo-full-stack-3-formativa4-recetas:latest
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@legx51juninivtkl_medium?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Octubre$2024
    networks:
      - app-network
    restart: on-failure
  
  frontend:
    container_name: frontend
    image: ingfaraya/desarrollo-full-stack-3-formativa4-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge